# Hexo Configuration

# Site
title: uinanlucky
subtitle: ''
description: 'A warm wiki blog'
keywords:
author: uinanlucky
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
url: https://iam-vampire.github.io/uinanlucky.github.io
root: /uinanlucky.github.io/
permalink: wiki/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
skip_render:
  - README.md

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Auto directory categorize (from hexo-directory-category)
auto_dir_categorize:
  enable: true
  force: true

# JsonContent for search
jsonContent:
  meta: false
  pages:
    title: true
    date: true
    path: true
    text: true
  posts:
    title: true
    date: true
    path: true
    text: true
    tags: true
    categories: true
  ignore:
    - 404.html

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Extensions
theme: wikiwarm

# Deployment
deploy:
  type: git
  repo: https://github.com/Iam-Vampire/uinanlucky.github.io.git
  branch: gh-pages
